environment: &environment
    docker:
        - image: ubuntu:latest

workspace_root: &workspace_root
    /tmp/workspace

attach_workspace: &attach_workspace
    attach_workspace:
        at: *workspace_root

version: 2
jobs:
    build:
        <<: *environment
        steps:
            - checkout
            - run:
                name: Current Time
                command: date
            - run:
                name: Install Dependencies
                command: |
                    apt-get update
                    apt-get install gcc -y
                    apt-get install make
            - run:
                name: Compiler Version
                command: gcc -v
            - run:
                name: Compile (User space)
                command: |
                    cd user_space_example
                    make all
    test:
        <<: *environment
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: |
                    apt-get update
                    apt-get install gcc -y
                    apt-get install make
                    apt-get install zip -y
            - run: |
                    cd user_space_example
                    make all
            - run:
                name: Run user space program
                command: make run

workflows:
    version: 2
    build_test:
        jobs:
            - build
            - test:
                requires:
                    - build
